Repository GDSC-KNU/Code2CV-BE, pull requests merged in 2024-05, with the labels that each got.

#5 [Fix]: 라벨 할당
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feat.yaml
  .github/pull_request_template.md
Labels: :book: : 리뷰 요청

#7 [Feat]: CheckStyle 적용
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
  config/checkstyle/naver-intellij-formatter.xml
  src/main/java/team/gdsc/code2cv/Code2CvApplication.java
  src/main/java/team/gdsc/code2cv/core/controller/config/SwaggerConfig.java
  src/main/java/team/gdsc/code2cv/core/controller/error/ErrorCode.java
  src/main/java/team/gdsc/code2cv/core/controller/error/ErrorResponse.java
  src/main/java/team/gdsc/code2cv/core/dto/response/PagingResponse.java
  src/main/java/team/gdsc/code2cv/core/exception/ResourceNotFoundException.java
  src/main/java/team/gdsc/code2cv/core/jwt/JwtProvider.java
  src/main/java/team/gdsc/code2cv/core/jwt/JwtToken.java
  src/main/java/team/gdsc/code2cv/core/jwt/JwtUser.java
  src/main/java/team/gdsc/code2cv/core/jwt/Role.java
  src/main/java/team/gdsc/code2cv/core/repository/JpaConfig.java
  src/main/java/team/gdsc/code2cv/core/security/JwtAccessDeniedHandler.java
  src/main/java/team/gdsc/code2cv/core/security/JwtAuthenticationEntryPoint.java
  src/main/java/team/gdsc/code2cv/core/security/JwtAuthenticationFilter.java
  src/main/java/team/gdsc/code2cv/core/security/JwtDetails.java
  src/main/java/team/gdsc/code2cv/core/security/WebSecurityConfig.java
  src/test/java/team/gdsc/code2cv/Code2CvApplicationTests.java
Labels: :eyeglasses: 리뷰중

#16 [Feat]: 유효성 검사 SelfValidating 추상 클래스 추가
  src/main/java/team/gdsc/code2cv/core/utils/SelfValidating.java
Labels: :sparkles: 기능

#17 [Feat] Issue/#13 중간 PR
  src/main/java/team/gdsc/code2cv/core/exception/ExternalServerCommunicationException.java
  src/main/java/team/gdsc/code2cv/core/exception/TokenExpiredException.java
  src/main/java/team/gdsc/code2cv/core/utils/Pair.java
  src/main/java/team/gdsc/code2cv/core/utils/SelfValidating.java
  src/main/java/team/gdsc/code2cv/feature/project/domain/ProjectAnalysisCreate.java
  src/main/java/team/gdsc/code2cv/feature/project/domain/ProjectContributionAreaCreate.java
  src/main/java/team/gdsc/code2cv/feature/project/entity/ProjectAnalysis.java
  src/main/java/team/gdsc/code2cv/feature/project/entity/ProjectContributionArea.java
  src/main/java/team/gdsc/code2cv/feature/project/repository/GithubRepositoryClient.java
  src/main/java/team/gdsc/code2cv/feature/project/repository/ProjectAnalysisRepository.java
  src/main/java/team/gdsc/code2cv/feature/project/repository/ProjectContributionAreaRepository.java
  src/main/java/team/gdsc/code2cv/global/client/github/GithubRestApiClient.java
  src/main/java/team/gdsc/code2cv/global/client/github/GithubRestApiClientConfig.java
  src/main/java/team/gdsc/code2cv/global/client/github/response/GithubCommitInfoModel.java
  src/main/java/team/gdsc/code2cv/global/client/github/response/GithubRepositoryInfoModel.java
  src/main/java/team/gdsc/code2cv/global/controller/error/ApiExceptionControllerAdvice.java
  src/main/java/team/gdsc/code2cv/global/repository/JpaConfig.java
  src/test/java/team/gdsc/code2cv/feature/project/repository/GithubRepositoryClientTest.java
Labels: :sparkles: 기능, :book: : 리뷰 요청
